# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20171014_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmembers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='addmembers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='addmembers',
            name='password',
        ),
        migrations.AddField(
            model_name='addmembers',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
