# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171014_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(upload_to='userprofile/cv'),
        ),
    ]
