# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20171014_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmembers',
            name='member',
        ),
        migrations.AddField(
            model_name='addmembers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='addmembers',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='addmembers',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addmembers',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addmembers',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addmembers',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addmembers',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addmembers',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addmembers',
            name='landline',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addmembers',
            name='office_address',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='addmembers',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='company/members/profile_pic'),
        ),
        migrations.AlterField(
            model_name='addmembers',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
