# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20171014_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
