# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20171015_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='user_profile/profile_pic/logo-2.jpg', upload_to='user_profile/profile_pic'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(default='userprofile/cv/google.png', upload_to='userprofile/cv'),
        ),
    ]
