# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_auto_20171014_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_position', models.CharField(max_length=255)),
                ('job_qualification', models.CharField(max_length=255)),
                ('no_of_vacancy', models.IntegerField()),
                ('job_description', models.TextField()),
                ('job_created_date', models.DateField(default=datetime.datetime.now)),
                ('job_last_date', models.DateField()),
                ('company_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.AddMembers')),
            ],
        ),
    ]
