# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20171014_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjob',
            name='marks_requred',
            field=models.IntegerField(null=True),
        ),
    ]
