# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_createjob_marks_requred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createjob',
            old_name='marks_requred',
            new_name='marks_required',
        ),
    ]
