# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20171015_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='marks_required',
            field=models.IntegerField(null=True),
        ),
    ]
