# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20171015_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjob',
            name='skill_required',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
