# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_createjob_skill_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='skill_required',
            field=models.CharField(max_length=100),
        ),
    ]
