# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20171014_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttest',
            name='subject',
            field=models.CharField(max_length=1024),
        ),
    ]
