# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0002_auto_20171013_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('representative', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('contact_no', models.IntegerField()),
                ('office_address', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
